name: Build
on: [push, pull_request]

jobs:
  build:
    uses: FoundatioFx/Foundatio/.github/workflows/build-workflow.yml@master
    secrets: inherit

  buildverifydocker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Start Services
      if: hashFiles('docker-compose.yml') != ''
      run: docker compose up -d && docker compose up ready || true
    - name: Verify Services
      if: hashFiles('docker-compose.yml') != ''
      run: docker run -it --network=host edenhill/kcat:1.7.1 -b localhost:9092 -L
