name: Build
on: [push, pull_request]

jobs:
  build:
    uses: FoundatioFx/Foundatio/.github/workflows/build-workflow.yml@master
    secrets: inherit

  buildverifydocker:
    runs-on: ubuntu-latest
    steps:
    - name: Start Services
      run: docker compose up -d && docker compose up ready || true
    - name: Sleep
      run: sleep 10
    - name: Verify Services
      run: docker run --network=host edenhill/kcat:1.7.1 -b localhost:9092 -L -T
